### ISSUE TITLE
Support for OFS "v3"?

### ISSUE THREAD

**Issue by waddlesplash** [pablomarx/hobbitbeos#1]
It seems that the BeOS "Developer Release 8" image (which can be found online in some places) uses OFS3 (Preview Release 1 and after use BFS). The BeOS R5 release still contains an "OFS" driver, but I didn't manage to get it to mount the DR8 image for whatever reason. It turns out the basic structure isn't too different; here's the minimal changes I made (besides removing the version check) to get the `ofs-extractor` to be able to read files out of the DR8 image:

```diff
diff --git a/ofs-extractor/ofs-extractor.h b/ofs-extractor/ofs-extractor.h
index f1bd63c..b5cd203 100644
--- a/ofs-extractor/ofs-extractor.h
+++ b/ofs-extractor/ofs-extractor.h
@@ -45,8 +45,8 @@ typedef struct	TableOfContents {
 	uint32_t unknown3[109];
 } TableOfContents;
 
-typedef struct	FileEntry {
-	char     FileName[32];
+typedef struct FileEntry3 {
+	char     FileName[64];
 	uint32_t FirstAllocList;
 	uint32_t LastAllocList;
 	uint32_t FileType;
@@ -55,6 +55,7 @@ typedef struct	FileEntry {
 	uint32_t LogicalSize;
 	uint32_t PhysicalSize;
 	uint32_t Creator;
+	char	 unknown1[32];
 } FileEntry;
 
 typedef struct	DirectoryBlock {
```

Of course this is a hack, and I didn't check too much to see if all the other on-disk structures correspond, but the files that got dumped all "looked correct" to me, anyway.

**Comment by pablomarx** [comment]
Very nice! Was the VersionNumber in the TOC set to 3? 

Time permitting this weekend, I'll try to get this tool working with both versions.

**Comment by waddlesplash** [comment]
I believe it was, yes.

**Comment by pablomarx** [comment]
Your changes seem to work great for both V2 (DR6) and V3 (DR7).

**Comment by pablomarx** [comment]
I updated the tool via commit f283695, and tested it with the following images:

* Hobbit-9308000044.img (OFS V1)
* Hobbit-9308000044b.img (OFS V1)
* hobbit-9308000058.img (OFS V1)
* hobbit-930800009.img (OFS V1)
* BeOS_1_1d6.iso (OFS V2)
* BeOS_1_1d7.iso (OFS V3)
* BeOS_1_1d7_1.iso (OFS V3)
